ame: Master Publish

on:
    push:
        branches: [master]

jobs:
    init:
        if: "!contains(github.event.head_commit.author.name, 'GitHub Action') && !contains(github.event.head_commit.message, '[skip ci]')"
        runs-on: ubuntu-latest
        timeout-minutes: 60

        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 4
            - uses: actions/setup-node@v3
              with:
                  node-version: "20"
                  check-latest: true
            - run: git fetch --prune --unshallow
            - run: |
                  make yarn_install

            - name: Setup Git
              uses: webfactory/ssh-agent@v0.4.1
              with:
                  ssh-private-key: ${{ secrets.GHA_DEPLOY_KEY }}

            - name: Lerna Publish
              if: "success() && !contains(github.event.head_commit.author.name, 'GitHub Action')"
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  NODE_ENV: production
              run: |
                  git config user.email "action@github.com"
                  git config user.name "GitHub Action"
                  git remote set-url origin "git@github.com:${{ github.repository }}"
                  git checkout -- .
                  yarn publish-stable